import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo } from "react";
import { FlatList, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { EmptyState, IconButton, ScreenTitle } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { useI18n } from "@/lib/i18n";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

export default function LocationsScreen() {
  const colors = useColors(); const { locations, classes } = useDars(); const { language, isRTL } = useI18n(); const insets = useSafeAreaInsets(); const list = useMemo(() => [...locations].sort((a, b) => a.name.localeCompare(b.name)), [locations]); const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={list} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) + 16 }]} ListHeaderComponent={<View style={styles.header}><ScreenTitle title={language === "ar" ? "الأماكن" : "Locations"} action={<IconButton icon="add" label={language === "ar" ? "أضف مكاناً" : "Add location"} onPress={() => router.push("/location/form" as never)} />} /></View>} renderItem={({ item }) => <MotionPressable accessibilityRole="button" onPress={() => router.push(`/location/${item.id}` as never)} style={({ pressed }) => [styles.card, isRTL && styles.rowReverse, { backgroundColor: colors.surface, borderColor: colors.border, shadowColor: "#000", opacity: pressed ? 0.66 : 1 }]}><View style={[styles.icon, { backgroundColor: colors.wash }]}><MaterialIcons name="location-on" size={19} color={colors.tint} /></View><View style={styles.copy}><Text numberOfLines={1} style={[styles.name, { color: colors.text }, writing]}>{item.name}</Text><Text numberOfLines={1} style={[styles.subtitle, { color: colors.muted }, writing]}>{item.city} · {item.area}</Text></View><Text style={[styles.count, { color: colors.muted, writingDirection: isRTL ? "rtl" : "ltr" }]}>{classes.filter((entry) => entry.locationId === item.id).length} {language === "ar" ? "دروس" : "classes"}</Text><Pressable accessibilityRole="button" accessibilityLabel={language === "ar" ? "الخريطة" : "Map"} disabled={!item.mapLink} onPress={() => item.mapLink ? void Linking.openURL(item.mapLink) : undefined} style={({ pressed }) => [styles.mapButton, { borderColor: colors.border, opacity: item.mapLink ? (pressed ? 0.64 : 1) : 0.35 }]}><MaterialIcons name="map" size={15} color={colors.text} /><Text style={[styles.mapText, { color: colors.text }]}>{language === "ar" ? "خريطة" : "Map"}</Text></Pressable></MotionPressable>} ListEmptyComponent={<EmptyState icon="location-on" title={language === "ar" ? "لا توجد أماكن" : "No locations found"} message={language === "ar" ? "أضف مكاناً لإقامة الدروس." : "Add a class location to begin."} actionLabel={language === "ar" ? "أضف مكاناً" : "Add location"} onAction={() => router.push("/location/form" as never)} />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 16 }, rowReverse: { flexDirection: "row-reverse" }, header: { marginBottom: 1 }, card: { alignItems: "center", borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 10, marginBottom: 12, minHeight: 72, padding: 13, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 8 }, icon: { alignItems: "center", borderRadius: 20, height: 40, justifyContent: "center", width: 40 }, copy: { flex: 1, minWidth: 0 }, name: { fontSize: 14.5, fontWeight: "600" }, subtitle: { fontSize: 12, marginTop: 2 }, count: { fontSize: 10.5, maxWidth: 44, textAlign: "right" }, mapButton: { alignItems: "center", borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 3, minHeight: 31, paddingHorizontal: 7 }, mapText: { fontSize: 10.5, fontWeight: "500" } });
