import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ClassCard, EmptyState, IconButton, ScreenTitle, SearchField } from "@/components/dars-ui";
import { OptionPicker } from "@/components/form-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { classMatchesQuery } from "@/lib/dars-utils";
import { useDars } from "@/lib/dars-context";

export default function SearchScreen() {
  const colors = useColors(); const { classes, teachers, books, locations } = useDars(); const [query, setQuery] = useState(""); const [teacher, setTeacher] = useState(""); const [subject, setSubject] = useState(""); const [book, setBook] = useState(""); const [location, setLocation] = useState(""); const [city, setCity] = useState(""); const [status, setStatus] = useState("upcoming");
  const data = useMemo(() => classes.filter((item) => classMatchesQuery(item, { teachers, books, locations }, query) && (!teacher || item.teacherId === teacher) && (!subject || item.subject === subject) && (!book || item.bookId === book) && (!location || item.locationId === location) && (!city || item.city === city) && (!status || item.status === status)), [book, city, classes, location, query, status, subject, teacher, teachers, books, locations]);
  const header = <View style={styles.header}><ScreenTitle eyebrow="Find the right lesson" title="Search & filter" action={<IconButton icon="close" label="Close search" onPress={() => router.back()} />} /><SearchField value={query} onChangeText={setQuery} placeholder="Class, scholar, book, place…" /><View style={[styles.filters, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.filterHeading}><Text style={[styles.filterTitle, { color: colors.text }]}>Refine results</Text><Pressable onPress={() => { setTeacher(""); setSubject(""); setBook(""); setLocation(""); setCity(""); setStatus(""); }}><Text style={[styles.clear, { color: colors.tint }]}>Clear</Text></Pressable></View><OptionPicker value={teacher} options={[{ label: "All teachers", value: "" }, ...teachers.map((item) => ({ label: item.name, value: item.id }))]} onSelect={setTeacher} placeholder="All teachers" /><OptionPicker value={subject} options={[{ label: "All subjects", value: "" }, ...Array.from(new Set(classes.map((item) => item.subject))).map((item) => ({ label: item, value: item }))]} onSelect={setSubject} placeholder="All subjects" /><OptionPicker value={book} options={[{ label: "All books", value: "" }, ...books.map((item) => ({ label: item.name, value: item.id }))]} onSelect={setBook} placeholder="All books" /><OptionPicker value={location} options={[{ label: "All locations", value: "" }, ...locations.map((item) => ({ label: item.name, value: item.id }))]} onSelect={setLocation} placeholder="All locations" /><OptionPicker value={city} options={[{ label: "All cities", value: "" }, ...Array.from(new Set(locations.map((item) => item.city))).map((item) => ({ label: item, value: item }))]} onSelect={setCity} placeholder="All cities" /><OptionPicker value={status} options={[{ label: "Any status", value: "" }, { label: "Upcoming", value: "upcoming" }, { label: "Completed", value: "completed" }, { label: "Cancelled", value: "cancelled" }]} onSelect={setStatus} placeholder="Class status" /></View><Text style={[styles.resultCount, { color: colors.muted }]}>{data.length} matching classes</Text></View>;
  return <ScreenContainer><FlatList data={data} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={header} renderItem={({ item }) => <View style={styles.item}><ClassCard item={item} teachers={teachers} books={books} locations={locations} /></View>} ListEmptyComponent={<EmptyState title="No matches yet" message="Broaden a filter or search using a different class detail." />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 48 }, header: { gap: 16, paddingBottom: 10 }, filters: { borderRadius: 20, borderWidth: 1, gap: 10, padding: 14 }, filterHeading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 2 }, filterTitle: { fontSize: 15, fontWeight: "800" }, clear: { fontSize: 13, fontWeight: "800" }, resultCount: { fontSize: 12, fontWeight: "700", marginTop: 2 }, item: { marginTop: 10 } });
