import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { IconButton, ScreenTitle } from "@/components/dars-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { haptic } from "@/lib/haptics";
import { useI18n } from "@/lib/i18n";
import { goBackOrHome } from "@/lib/navigation";
import { requestReminderPermission } from "@/lib/reminders";
import { useThemeContext } from "@/lib/theme-provider";
import type { DateDisplay } from "@/lib/types/dars";

export default function SettingsScreen() {
  const colors = useColors(); const { colorScheme, setColorScheme } = useThemeContext(); const { preferences, updatePreferences } = useDars(); const { t, isRTL, language } = useI18n(); const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  const setReminders = async (enabled: boolean) => { if (enabled) { const permission = await requestReminderPermission(); if (permission !== "granted") { const message = permission === "unavailable" ? (language === "ar" ? "التذكيرات متاحة على جهاز iOS أو Android فقط." : "Reminders are available only on an iOS or Android device.") : (language === "ar" ? "اسمح بالإشعارات من إعدادات الجهاز ثم عُد إلى دارس هَب." : "Allow notifications in device settings, then return to DarsHub."); Alert.alert(t("permissionRequired"), message, permission === "denied" ? [{ text: t("notificationSettings"), onPress: () => void Linking.openSettings() }, { text: language === "ar" ? "إلغاء" : "Cancel", style: "cancel" }] : [{ text: "OK" }]); return; } } haptic.selection(); updatePreferences({ remindersEnabled: enabled }); };
  const Choice = ({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) => <Pressable onPress={() => { haptic.selection(); onPress(); }} style={({ pressed }) => [styles.choice, { backgroundColor: selected ? colors.tint : "transparent", opacity: pressed ? 0.68 : 1 }]}><Text style={[styles.choiceText, { color: selected ? colors.background : colors.muted, writingDirection: isRTL ? "rtl" : "ltr" }]}>{label}</Text></Pressable>;
  const Group = ({ children }: { children: React.ReactNode }) => <View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}>{children}</View>;
  const Row = ({ icon, title, detail, children, last = false }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; detail?: string; children: React.ReactNode; last?: boolean }) => <View style={[styles.row, isRTL && styles.rowReverse, !last && { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }]}><View style={[styles.iconBox, { backgroundColor: colors.wash }]}><MaterialIcons name={icon} size={19} color={colors.tint} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: colors.text }, writing]}>{title}</Text>{detail ? <Text style={[styles.rowDetail, { color: colors.muted }, writing]}>{detail}</Text> : null}</View>{children}</View>;
  const label = (value: string) => <Text style={[styles.sectionLabel, { color: colors.muted }, writing]}>{isRTL ? value : value.toUpperCase()}</Text>;
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenTitle title={t("settings")} action={<IconButton icon={isRTL ? "arrow-forward" : "arrow-back"} label={t("back")} onPress={goBackOrHome} />} />{label(language === "ar" ? "المظهر" : "Appearance")}<Group><Row icon="dark-mode" title={t("darkTheme")} detail={language === "ar" ? "تدرّج هادئ للمساء" : "A calm evening palette"} last><Switch value={colorScheme === "dark"} onValueChange={(value) => { haptic.selection(); setColorScheme(value ? "dark" : "light"); }} trackColor={{ false: colors.border, true: colors.tint }} thumbColor={colors.surface} /></Row></Group>{label(language === "ar" ? "اللغة والتاريخ" : "Language & dates")}<Group><Row icon="translate" title={t("interfaceLanguage")} last><View style={[styles.segment, isRTL && styles.rowReverse, { backgroundColor: colors.wash }]}><Choice label="English" selected={language === "en"} onPress={() => updatePreferences({ appLanguage: "en", dateLanguage: "en" })} /><Choice label="العربية" selected={language === "ar"} onPress={() => updatePreferences({ appLanguage: "ar", dateLanguage: "ar" })} /></View></Row><View style={[styles.inlineChoice, isRTL && styles.rowReverse]}><Text style={[styles.inlineLabel, { color: colors.text }, writing]}>{t("dateStyle")}</Text><View style={[styles.segment, isRTL && styles.rowReverse, { backgroundColor: colors.wash }]}>{(["gregorian", "dual", "hijri"] as DateDisplay[]).map((mode) => <Choice key={mode} label={mode === "gregorian" ? "G" : mode === "dual" ? "G/H" : "H"} selected={preferences.dateDisplay === mode} onPress={() => updatePreferences({ dateDisplay: mode })} />)}</View></View></Group>{label(language === "ar" ? "التذكيرات" : "Reminders")}<Group><Row icon="notifications-none" title={t("classReminders")} detail={preferences.remindersEnabled ? t("reminderEnabled") : t("off")} last={!preferences.remindersEnabled}><Switch value={preferences.remindersEnabled} onValueChange={setReminders} trackColor={{ false: colors.border, true: colors.tint }} thumbColor={colors.surface} /></Row>{preferences.remindersEnabled ? <View style={[styles.inlineChoice, isRTL && styles.rowReverse]}><Text style={[styles.inlineLabel, { color: colors.text }, writing]}>{language === "ar" ? "قبل الدرس" : "Before class"}</Text><View style={[styles.segment, isRTL && styles.rowReverse, { backgroundColor: colors.wash }]}>{([10, 30, 60] as const).map((minutes) => <Choice key={minutes} label={`${minutes}m`} selected={preferences.reminderLeadMinutes === minutes} onPress={() => updatePreferences({ reminderLeadMinutes: minutes })} />)}</View></View> : null}</Group>{label(language === "ar" ? "حول" : "About")}<Group><Row icon="auto-stories" title="DarsHub" detail={language === "ar" ? "رفيق الدراسة الخاص بك" : "Your private study companion"} last><MaterialIcons name="check-circle" size={20} color={colors.success} /></Row></Group></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 14, padding: 20, paddingBottom: 48, paddingTop: 6 }, rowReverse: { flexDirection: "row-reverse" }, sectionLabel: { fontSize: 10.5, fontWeight: "800", letterSpacing: 0.85, marginBottom: -6, marginTop: 2 }, group: { borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, overflow: "hidden" }, row: { alignItems: "center", flexDirection: "row", gap: 12, minHeight: 72, paddingHorizontal: 14, paddingVertical: 12 }, iconBox: { alignItems: "center", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, rowCopy: { flex: 1, gap: 2 }, rowTitle: { fontSize: 15.5, fontWeight: "700" }, rowDetail: { fontSize: 12, lineHeight: 17 }, segment: { borderRadius: 10, flexDirection: "row", padding: 3 }, choice: { alignItems: "center", borderRadius: 8, flex: 1, justifyContent: "center", minHeight: 32, paddingHorizontal: 9 }, choiceText: { fontSize: 11.5, fontWeight: "800" }, inlineChoice: { alignItems: "center", flexDirection: "row", gap: 12, minHeight: 64, paddingHorizontal: 14, paddingVertical: 12 }, inlineLabel: { flex: 1, fontSize: 14, fontWeight: "700" } });
