import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ReactNode, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useColors } from "@/hooks/use-colors";
import { haptic } from "@/lib/haptics";
import { useI18n } from "@/lib/i18n";

export function FormSection({ title, children }: { title: string; children: ReactNode }) { const colors = useColors(); const { isRTL } = useI18n(); return <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.muted, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{isRTL ? title : title.toUpperCase()}</Text><View style={[styles.sectionBody, { borderTopColor: colors.border }]}>{children}</View></View>; }
export function TextField({ label, value, onChangeText, placeholder, multiline = false, required = false }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; multiline?: boolean; required?: boolean }) { const colors = useColors(); const { isRTL } = useI18n(); return <View style={styles.field}><Text style={[styles.label, { color: colors.text, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{label}{required ? <Text style={{ color: colors.error }}> *</Text> : null}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} multiline={multiline} style={[styles.input, multiline && styles.textarea, { color: colors.text, backgroundColor: colors.wash, borderColor: colors.border, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]} returnKeyType={multiline ? "default" : "done"} /></View>; }
export function PickerField({ label, value, options, onSelect, placeholder = "Select" }: { label: string; value: string; options: { label: string; value: string }[]; onSelect: (value: string) => void; placeholder?: string }) { const colors = useColors(); const { isRTL } = useI18n(); return <View style={styles.field}><Text style={[styles.label, { color: colors.text, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{label}</Text><OptionPicker value={value} options={options} onSelect={onSelect} placeholder={placeholder} /></View>; }
export function OptionPicker({ value, options, onSelect, placeholder = "Select" }: { value: string; options: { label: string; value: string }[]; onSelect: (value: string) => void; placeholder?: string }) {
  const [visible, setVisible] = useState(false); const colors = useColors(); const { isRTL } = useI18n(); const insets = useSafeAreaInsets(); const display = options.find((option) => option.value === value)?.label ?? placeholder;
  return <><Pressable accessibilityRole="button" onPress={() => { haptic.light(); setVisible(true); }} style={({ pressed }) => [styles.picker, isRTL && styles.rowReverse, { backgroundColor: colors.wash, borderColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><Text numberOfLines={1} style={[styles.pickerText, { color: value ? colors.text : colors.muted, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{display}</Text><MaterialIcons name="expand-more" size={21} color={colors.muted} /></Pressable><Modal transparent visible={visible} animationType="slide" statusBarTranslucent onRequestClose={() => setVisible(false)}><View style={styles.modalShade}><Pressable accessibilityLabel="Close options" onPress={() => setVisible(false)} style={StyleSheet.absoluteFill} /><View style={[styles.sheet, { backgroundColor: colors.surface }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><View style={[styles.sheetHeader, isRTL && styles.rowReverse]}><Text style={[styles.sheetTitle, { color: colors.text, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{placeholder}</Text><Pressable accessibilityLabel="Close options" onPress={() => setVisible(false)} hitSlop={10}><MaterialIcons name="close" size={22} color={colors.muted} /></Pressable></View><ScrollView bounces={false} contentContainerStyle={{ paddingBottom: Math.max(insets.bottom, 12) }}>{options.map((option) => <Pressable key={option.value} onPress={() => { haptic.selection(); onSelect(option.value); setVisible(false); }} style={({ pressed }) => [styles.option, isRTL && styles.rowReverse, { borderBottomColor: colors.border, backgroundColor: value === option.value ? colors.wash : "transparent", opacity: pressed ? 0.65 : 1 }]}><Text style={[styles.optionText, { color: colors.text, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{option.label}</Text>{value === option.value ? <MaterialIcons name="check" size={20} color={colors.tint} /> : null}</Pressable>)}</ScrollView></View></View></Modal></>;
}

const styles = StyleSheet.create({ rowReverse: { flexDirection: "row-reverse" }, section: { gap: 9, marginBottom: 25 }, sectionTitle: { fontSize: 10.5, fontWeight: "800", letterSpacing: 0.75 }, sectionBody: { borderTopWidth: StyleSheet.hairlineWidth, gap: 15, paddingTop: 15 }, field: { gap: 7 }, label: { fontSize: 13, fontWeight: "700" }, input: { borderRadius: 10, borderWidth: 1, fontSize: 15, minHeight: 48, paddingHorizontal: 13, paddingVertical: 10 }, textarea: { minHeight: 98, textAlignVertical: "top" }, picker: { alignItems: "center", borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 48, paddingHorizontal: 13 }, pickerText: { flex: 1, fontSize: 15 }, modalShade: { backgroundColor: "rgba(10,20,16,0.28)", flex: 1, justifyContent: "flex-end" }, sheet: { borderTopLeftRadius: 22, borderTopRightRadius: 22, maxHeight: "72%", overflow: "hidden", paddingTop: 9 }, handle: { alignSelf: "center", borderRadius: 99, height: 4, marginBottom: 10, width: 34 }, sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 11 }, sheetTitle: { flex: 1, fontSize: 17, fontWeight: "800" }, option: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", minHeight: 56, paddingHorizontal: 20 }, optionText: { flex: 1, fontSize: 15, fontWeight: "600" } });
