import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";

export function StudySpaceGate({ children }: { children: React.ReactNode }) {
  const colors = useColors(); const { dataStatus, saveStatus, saveError, retryHydration, retrySave } = useDars();
  if (dataStatus === "ready") return <>{children}{saveStatus === "error" ? <View style={[styles.saveNotice, { backgroundColor: colors.surface, borderColor: colors.error }]}><Text style={[styles.saveText, { color: colors.text }]}>Your latest change has not been saved.</Text><Pressable accessibilityRole="button" onPress={retrySave} style={({ pressed }) => [styles.retry, { opacity: pressed ? 0.65 : 1 }]}><Text style={[styles.retryText, { color: colors.tint }]}>Retry</Text></Pressable></View> : null}</>;
  const failed = dataStatus === "error";
  return <View style={[styles.container, { backgroundColor: colors.background }]}><View style={styles.content}>{failed ? null : <ActivityIndicator color={colors.tint} size="small" />}<Text style={[styles.title, { color: colors.text }]}>{failed ? "Dars could not load your study space" : "Opening your study space"}</Text><Text style={[styles.message, { color: colors.muted }]}>{failed ? saveError ?? "Your data is still on this device. Try again before making changes." : "Loading your local classes, teachers, books, and locations…"}</Text>{failed ? <Pressable accessibilityRole="button" onPress={retryHydration} style={({ pressed }) => [styles.action, { backgroundColor: colors.tint, opacity: pressed ? 0.76 : 1 }]}><Text style={[styles.actionText, { color: colors.onPrimary }]}>Try again</Text></Pressable> : null}</View></View>;
}

const styles = StyleSheet.create({ container: { flex: 1, justifyContent: "center", padding: 28 }, content: { alignItems: "center", gap: 12 }, title: { fontSize: 19, fontWeight: "700", textAlign: "center" }, message: { fontSize: 14, lineHeight: 20, maxWidth: 300, textAlign: "center" }, action: { alignItems: "center", borderRadius: 12, justifyContent: "center", marginTop: 4, minHeight: 46, minWidth: 132, paddingHorizontal: 16 }, actionText: { fontSize: 14, fontWeight: "700" }, saveNotice: { alignItems: "center", borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, bottom: 18, flexDirection: "row", gap: 12, left: 16, paddingHorizontal: 14, paddingVertical: 11, position: "absolute", right: 16, shadowColor: "#000", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.12, shadowRadius: 10 }, saveText: { flex: 1, fontSize: 12.5, fontWeight: "600" }, retry: { minHeight: 32, justifyContent: "center" }, retryText: { fontSize: 13, fontWeight: "700" } });
