import { createContext, useContext, useMemo } from "react";
import { useDars } from "@/lib/dars-context";

const copy = {
  en: { home: "Home", schedule: "Schedule", add: "Add", teachers: "Teachers", more: "More", settings: "Settings", greeting: "Assalamu alaykum", studySpace: "Your study space", scheduleSubtitle: "Your next lesson is ready when you are.", firstSteps: "First steps", buildStudySpace: "Build your study space", setupDescription: "Keep the people, books, and places behind each dars in one calm place.", yourAgenda: "Your agenda", upcomingClasses: "Upcoming classes", yourSchedule: "Your schedule", today: "Today", thisWeek: "This week", all: "All", addClass: "Add a class", noClassToday: "No class today", clearWeek: "A clear week ahead", classDetails: "Class details", reminder: "Reminder", off: "Off", upcoming: "Upcoming", completed: "Completed", cancelled: "Cancelled", darkTheme: "Dark theme", calendar: "Calendar", interfaceLanguage: "Interface language", dateStyle: "Date style", dateLanguage: "Date language", classReminders: "Class reminders", enableReminders: "Enable reminders", reminderEnabled: "Scheduled for upcoming classes", permissionRequired: "Notifications need permission", notificationSettings: "Open device settings", back: "Back", planWithIntention: "Plan with intention", studyLibrary: "Study library", books: "Books", locations: "Locations", searchFilter: "Search & filter", findClass: "Find a class", app: "App", themeAndData: "Theme and local data", classCount: "class", classesCount: "classes", noClassesWeek: "There are no upcoming classes in the next seven days.", noClassTodayDescription: "Nothing is planned for today. Add a class whenever you are ready.", teacherPending: "Teacher pending", locationPending: "Location pending" },
  ar: { home: "الرئيسية", schedule: "الجدول", add: "إضافة", teachers: "المعلمون", more: "المزيد", settings: "الإعدادات", greeting: "السلام عليكم", studySpace: "مساحة دراستك", scheduleSubtitle: "درسُك القادم جاهز عندما تكون مستعداً.", firstSteps: "الخطوات الأولى", buildStudySpace: "أنشئ مساحة دراستك", setupDescription: "احتفظ بالمعلمين والكتب والأماكن الخاصة بكل درس في مكان هادئ.", yourAgenda: "جدولك", upcomingClasses: "الدروس القادمة", yourSchedule: "جدولك الدراسي", today: "اليوم", thisWeek: "هذا الأسبوع", all: "الكل", addClass: "أضف درساً", noClassToday: "لا يوجد درس اليوم", clearWeek: "أسبوع هادئ أمامك", classDetails: "تفاصيل الدرس", reminder: "تذكير", off: "متوقف", upcoming: "قادم", completed: "مكتمل", cancelled: "ملغى", darkTheme: "المظهر الداكن", calendar: "التقويم", interfaceLanguage: "لغة التطبيق", dateStyle: "طريقة عرض التاريخ", dateLanguage: "لغة التاريخ", classReminders: "تذكيرات الدروس", enableReminders: "تفعيل التذكيرات", reminderEnabled: "مجدولة للدروس القادمة", permissionRequired: "تحتاج الإشعارات إلى إذن", notificationSettings: "افتح إعدادات الجهاز", back: "رجوع", planWithIntention: "رتّب دراستك بنية", studyLibrary: "مكتبة الدراسة", books: "الكتب", locations: "الأماكن", searchFilter: "البحث والتصفية", findClass: "ابحث عن درس", app: "التطبيق", themeAndData: "المظهر والبيانات المحلية", classCount: "درس", classesCount: "دروس", noClassesWeek: "لا توجد دروس قادمة خلال الأيام السبعة المقبلة.", noClassTodayDescription: "لا يوجد شيء مخطط لليوم. أضف درساً عندما تكون مستعداً.", teacherPending: "المعلم غير محدد", locationPending: "المكان غير محدد" },
} as const;

type CopyKey = keyof typeof copy.en;
type I18nValue = { language: "en" | "ar"; isRTL: boolean; t: (key: CopyKey) => string };
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const { preferences } = useDars();
  const value = useMemo<I18nValue>(() => ({ language: preferences.appLanguage, isRTL: preferences.appLanguage === "ar", t: (key) => copy[preferences.appLanguage][key] }), [preferences.appLanguage]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error("useI18n must be used within I18nProvider"); return value; }
