import * as Notifications from "expo-notifications";
import { Platform } from "react-native";
import type { DarsClass, DarsPreferences } from "@/lib/types/dars";
import { getReminderTime, getSchedulableClasses } from "@/lib/reminder-plan";

export type ReminderPermission = "granted" | "denied" | "undetermined" | "unavailable";
export type ReminderDiagnostics = { permission: ReminderPermission; scheduledClassReminders: number };
Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowBanner: true, shouldShowList: true, shouldPlaySound: true, shouldSetBadge: false }) });
let pendingSync: Promise<number> = Promise.resolve(0);

async function configureAndroidChannel() { if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("classes", { name: "Class reminders", description: "Reminders before your upcoming dars", importance: Notifications.AndroidImportance.HIGH, vibrationPattern: [0, 180, 90, 180], lightColor: "#164D3D", sound: "default" }); }
export async function getReminderPermission(): Promise<ReminderPermission> { if (Platform.OS === "web") return "unavailable"; await configureAndroidChannel(); const { status } = await Notifications.getPermissionsAsync(); return status === "granted" ? "granted" : status === "denied" ? "denied" : "undetermined"; }
export async function requestReminderPermission(): Promise<ReminderPermission> { const current = await getReminderPermission(); if (current === "granted" || current === "unavailable" || current === "denied") return current; const { status } = await Notifications.requestPermissionsAsync(); return status === "granted" ? "granted" : status === "denied" ? "denied" : "undetermined"; }
export function syncClassReminders(items: DarsClass[], preferences: DarsPreferences): Promise<number> { const run = async () => { if (Platform.OS === "web") return 0; const existing = await Notifications.getAllScheduledNotificationsAsync(); await Promise.all(existing.filter((request) => request.content.data?.source === "darshub-class").map((request) => Notifications.cancelScheduledNotificationAsync(request.identifier))); if (!preferences.remindersEnabled || await getReminderPermission() !== "granted") return 0; const upcoming = getSchedulableClasses(items, preferences.reminderLeadMinutes); await Promise.all(upcoming.map((item) => Notifications.scheduleNotificationAsync({ content: { title: "DarsHub reminder", body: `${item.title} starts in ${preferences.reminderLeadMinutes} minutes.`, sound: "default", data: { source: "darshub-class", classId: item.id } }, trigger: { type: "date", date: getReminderTime(item, preferences.reminderLeadMinutes), channelId: "classes" } as never }))); return upcoming.length; }; const queued = pendingSync.then(run, run); pendingSync = queued.catch(() => 0); return queued; }
export async function getReminderDiagnostics(): Promise<ReminderDiagnostics> { const permission = await getReminderPermission(); if (Platform.OS === "web") return { permission, scheduledClassReminders: 0 }; const requests = await Notifications.getAllScheduledNotificationsAsync(); return { permission, scheduledClassReminders: requests.filter((request) => request.content.data?.source === "darshub-class").length }; }
export async function scheduleReminderVerification(): Promise<ReminderPermission> { const permission = await requestReminderPermission(); if (permission !== "granted") return permission; await Notifications.scheduleNotificationAsync({ content: { title: "DarsHub reminder check", body: "Notifications are ready for your upcoming classes.", sound: "default", data: { source: "darshub-verification" } }, trigger: { type: "date", date: new Date(Date.now() + 7000), channelId: "classes" } as never }); return permission; }
export function observeReminderResponses(onOpenClass: (classId: string) => void) { if (Platform.OS === "web") return () => undefined; const open = (response: Notifications.NotificationResponse | null) => { const id = response?.notification.request.content.data?.classId; if (typeof id === "string") onOpenClass(id); }; void Notifications.getLastNotificationResponseAsync().then(open).catch(() => undefined); const subscription = Notifications.addNotificationResponseReceivedListener(open); return () => subscription.remove(); }
