import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, Linking, ScrollView, StyleSheet, Text, View } from "react-native";
import { PrimaryButton } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { formatClassDate, formatTime, getRef } from "@/lib/dars-utils";
import { useI18n } from "@/lib/i18n";
import { goBackOrHome } from "@/lib/navigation";
import { useDisplayPreferences } from "@/lib/use-display-preferences";

function InfoRow({ icon, label, value, last = false }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; value: string; last?: boolean }) { const colors = useColors(); const { isRTL } = useI18n(); return <View style={[styles.infoRow, !last && { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, isRTL && styles.rowReverse]}><MaterialIcons name={icon} size={18} color={colors.muted} /><View style={styles.infoCopy}><Text style={[styles.infoKey, { color: colors.muted, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{label}</Text><Text numberOfLines={2} style={[styles.infoValue, { color: colors.text, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{value}</Text></View></View>; }

export default function ClassDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const colors = useColors(); const { classes, teachers, books, locations } = useDars(); const { dateDisplay, locale } = useDisplayPreferences(); const { isRTL, language } = useI18n(); const item = classes.find((entry) => entry.id === id); const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  if (!item) return <ScreenContainer><View style={styles.missing}><Text style={[styles.missingTitle, { color: colors.text }, writing]}>{language === "ar" ? "الدرس غير متاح" : "Class unavailable"}</Text><PrimaryButton label={language === "ar" ? "رجوع" : "Go back"} onPress={goBackOrHome} /></View></ScreenContainer>;
  const teacher = getRef(teachers, item.teacherId); const book = getRef(books, item.bookId); const location = getRef(locations, item.locationId); const openMap = async () => { if (location?.mapLink) { await Linking.openURL(location.mapLink); return; } Alert.alert(language === "ar" ? "الخريطة غير متاحة" : "Map unavailable", language === "ar" ? "أضف رابط الخريطة للمكان أولاً." : "Add a map link to this location first."); }; const share = () => Alert.alert(language === "ar" ? "مشاركة الدرس" : "Share class", language === "ar" ? "ستتوفر روابط المشاركة قريباً." : "Sharing links will be available soon.");
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><View style={[styles.topBar, isRTL && styles.rowReverse]}><QuietIcon icon={isRTL ? "arrow-forward" : "arrow-back"} label={language === "ar" ? "رجوع" : "Back"} onPress={goBackOrHome} /><View style={[styles.utilities, isRTL && styles.rowReverse]}><QuietIcon icon="map" label={language === "ar" ? "الخريطة" : "Map"} onPress={openMap} /><QuietIcon icon="share" label={language === "ar" ? "مشاركة" : "Share"} onPress={share} /></View></View><View style={styles.summary}><Text style={[styles.overline, { color: colors.tint }, writing]}>{language === "ar" ? "درس" : "CLASS"}</Text><Text style={[styles.title, { color: colors.text }, writing]}>{item.title}</Text><Text style={[styles.teacher, { color: colors.muted }, writing]}>{teacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text><Text style={[styles.when, { color: colors.text }, writing]}>{formatClassDate(item.date, dateDisplay, locale)} · {formatTime(item.startTime, locale)}{item.endTime ? ` – ${formatTime(item.endTime, locale)}` : ""}</Text></View><View style={[styles.infoList, { borderBottomColor: colors.border, borderTopColor: colors.border }]}><InfoRow icon="menu-book" label={language === "ar" ? "الكتاب" : "Book"} value={book?.name ?? (language === "ar" ? "الكتاب غير محدد" : "Book pending")} /><InfoRow icon="location-on" label={language === "ar" ? "المكان" : "Location"} value={`${location?.name ?? (language === "ar" ? "المكان غير محدد" : "Location pending")}${location?.area || item.city ? ` · ${location?.area ?? item.city}` : ""}`} last={!item.notes} />{item.notes ? <InfoRow icon="notes" label={language === "ar" ? "ملاحظات" : "Notes"} value={item.notes} last /> : null}</View><PrimaryButton label={language === "ar" ? "تعديل الدرس" : "Edit class"} icon="edit" onPress={() => router.push({ pathname: "/class/form", params: { id: item.id } } as never)} /></ScrollView></ScreenContainer>;
}

function QuietIcon({ icon, label, onPress }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; onPress: () => void }) { const colors = useColors(); return <MotionPressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.quietIcon, { backgroundColor: colors.wash, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name={icon} size={19} color={colors.tint} /></MotionPressable>; }

const styles = StyleSheet.create({ scroll: { gap: 28, padding: 20, paddingBottom: 42 }, rowReverse: { flexDirection: "row-reverse" }, topBar: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, utilities: { flexDirection: "row", gap: 8 }, quietIcon: { alignItems: "center", borderRadius: 12, height: 42, justifyContent: "center", width: 42 }, summary: { gap: 7, paddingTop: 7 }, overline: { fontSize: 10.5, fontWeight: "800", letterSpacing: 0.8 }, title: { fontSize: 28, fontWeight: "700", letterSpacing: -0.85, lineHeight: 35, marginTop: 5 }, teacher: { fontSize: 15, lineHeight: 21 }, when: { fontSize: 13.5, fontWeight: "700", lineHeight: 20, marginTop: 7 }, infoList: { borderBottomWidth: StyleSheet.hairlineWidth, borderTopWidth: StyleSheet.hairlineWidth }, infoRow: { alignItems: "flex-start", flexDirection: "row", gap: 12, paddingVertical: 15 }, infoCopy: { flex: 1, gap: 4, minWidth: 0 }, infoKey: { fontSize: 11, fontWeight: "700" }, infoValue: { fontSize: 14, fontWeight: "600", lineHeight: 20 }, missing: { gap: 16, padding: 20, paddingTop: 100 }, missingTitle: { fontSize: 23, fontWeight: "700" } });
