import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, Linking, ScrollView, StyleSheet, Text, View } from "react-native";
import { IconButton, PrimaryButton } from "@/components/dars-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { formatClassDate, formatTime, getRef } from "@/lib/dars-utils";
import { useI18n } from "@/lib/i18n";
import { goBackOrHome } from "@/lib/navigation";
import { useDisplayPreferences } from "@/lib/use-display-preferences";

function MetaRow({ icon, value }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; value: string }) { const colors = useColors(); const { isRTL } = useI18n(); return <View style={[styles.metaRow, isRTL && styles.rowReverse]}><MaterialIcons name={icon} size={18} color={colors.tint} /><Text numberOfLines={1} style={[styles.metaText, { color: colors.text, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{value}</Text></View>; }

export default function ClassDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const colors = useColors(); const { classes, teachers, books, locations } = useDars(); const { dateDisplay, locale } = useDisplayPreferences(); const { isRTL, language } = useI18n(); const item = classes.find((entry) => entry.id === id); const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  if (!item) return <ScreenContainer><View style={styles.missing}><Text style={[styles.missingTitle, { color: colors.text }, writing]}>{language === "ar" ? "الدرس غير متاح" : "Class unavailable"}</Text><PrimaryButton label={language === "ar" ? "رجوع" : "Go back"} onPress={goBackOrHome} /></View></ScreenContainer>;
  const teacher = getRef(teachers, item.teacherId); const book = getRef(books, item.bookId); const location = getRef(locations, item.locationId); const openMap = async () => { if (location?.mapLink) { await Linking.openURL(location.mapLink); return; } Alert.alert(language === "ar" ? "الخريطة غير متاحة" : "Map unavailable", language === "ar" ? "أضف رابط الخريطة للمكان أولاً." : "Add a map link to this location first."); }; const share = () => Alert.alert(language === "ar" ? "مشاركة الدرس" : "Share class", language === "ar" ? "ستتوفر روابط المشاركة قريباً." : "Sharing links will be available soon.");
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={[styles.topbar, isRTL && styles.rowReverse]}><IconButton icon={isRTL ? "arrow-forward" : "arrow-back"} label={language === "ar" ? "رجوع" : "Back"} onPress={goBackOrHome} /><View style={[styles.utility, isRTL && styles.rowReverse]}><IconButton icon="map" label={language === "ar" ? "الخريطة" : "Map"} onPress={openMap} /><IconButton icon="share" label={language === "ar" ? "مشاركة" : "Share"} onPress={share} /></View></View><View style={styles.hero}><Text style={[styles.date, { color: colors.tint }, writing]}>{formatClassDate(item.date, dateDisplay, locale)}</Text><Text style={[styles.title, { color: colors.text }, writing]}>{item.title}</Text><Text style={[styles.teacher, { color: colors.muted }, writing]}>{teacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text></View><View style={[styles.timeLine, { borderColor: colors.border }, isRTL && styles.rowReverse]}><MaterialIcons name="schedule" size={17} color={colors.tint} /><Text style={[styles.time, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatTime(item.startTime, locale)}{item.endTime ? ` – ${formatTime(item.endTime, locale)}` : ""}</Text></View><View style={[styles.meta, { borderTopColor: colors.border, borderBottomColor: colors.border }]}><MetaRow icon="menu-book" value={book?.name ?? (language === "ar" ? "الكتاب غير محدد" : "Book pending")} /><MetaRow icon="location-on" value={`${location?.name ?? (language === "ar" ? "المكان غير محدد" : "Location pending")} · ${location?.area ?? item.city}`} /></View>{item.notes ? <View style={styles.notes}><Text style={[styles.notesLabel, { color: colors.muted }, writing]}>{language === "ar" ? "ملاحظات" : "Notes"}</Text><Text style={[styles.notesText, { color: colors.text }, writing]}>{item.notes}</Text></View> : null}<PrimaryButton label={language === "ar" ? "تعديل الدرس" : "Edit class"} icon="edit" onPress={() => router.push({ pathname: "/class/form", params: { id: item.id } } as never)} /></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 25, padding: 20, paddingBottom: 46, paddingTop: 10 }, rowReverse: { flexDirection: "row-reverse" }, topbar: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, utility: { flexDirection: "row", gap: 8 }, hero: { gap: 8, paddingTop: 8 }, date: { fontSize: 12, fontWeight: "800", letterSpacing: 0.45 }, title: { fontSize: 31, fontWeight: "700", letterSpacing: -1, lineHeight: 38 }, teacher: { fontSize: 15, fontWeight: "600" }, timeLine: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 9, paddingVertical: 17 }, time: { fontSize: 16, fontWeight: "700" }, meta: { borderBottomWidth: StyleSheet.hairlineWidth, borderTopWidth: StyleSheet.hairlineWidth }, metaRow: { alignItems: "center", flexDirection: "row", gap: 12, minHeight: 57 }, metaText: { flex: 1, fontSize: 15, fontWeight: "600" }, notes: { gap: 7 }, notesLabel: { fontSize: 11, fontWeight: "800", letterSpacing: 0.6 }, notesText: { fontSize: 14, lineHeight: 22 }, missing: { gap: 16, padding: 20, paddingTop: 100 }, missingTitle: { fontSize: 23, fontWeight: "700" } });
