import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo } from "react";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { EmptyState, IconButton } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { formatClassDate, formatTime, getNextClass, getRef, getUpcomingClasses } from "@/lib/dars-utils";
import { useDars } from "@/lib/dars-context";
import { useDisplayPreferences } from "@/lib/use-display-preferences";
import { useI18n } from "@/lib/i18n";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

const isoToday = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };

export default function HomeScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { classes, teachers, books, locations, isHydrated } = useDars(); const { dateDisplay, locale } = useDisplayPreferences(); const { language, isRTL } = useI18n(); const nextClass = getNextClass(classes); const upcoming = useMemo(() => getUpcomingClasses(classes).filter((item) => item.id !== nextClass?.id).slice(0, 3), [classes, nextClass?.id]);
  const hasReferences = Boolean(teachers.length && books.length && locations.length); const firstSetup = !teachers.length ? { route: "/teacher/form", label: language === "ar" ? "أضف معلماً" : "Add teacher" } : !books.length ? { route: "/book/form", label: language === "ar" ? "أضف كتاباً" : "Add book" } : { route: "/location/form", label: language === "ar" ? "أضف مكاناً" : "Add place" };
  const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  if (!isHydrated) return <ScreenContainer edges={["top", "left", "right"]}><View style={styles.loading}><View style={[styles.loadTitle, { backgroundColor: colors.wash }]} /><View style={[styles.loadHero, { backgroundColor: colors.wash }]} /></View></ScreenContainer>;
  const teacher = nextClass ? getRef(teachers, nextClass.teacherId) : undefined; const location = nextClass ? getRef(locations, nextClass.locationId) : undefined;
  const header = <View style={styles.header}><View style={[styles.topLine, isRTL && styles.rowReverse]}><View><Text style={[styles.greeting, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "مساء الخير" : "Good evening"}</Text><Text style={[styles.date, { color: colors.muted, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatClassDate(isoToday(), dateDisplay, locale)}</Text></View><IconButton icon="add" tone="primary" label={language === "ar" ? "أضف درساً" : "Add class"} onPress={() => router.push("/class/form" as never)} /></View>{nextClass ? <MotionPressable accessibilityRole="button" onPress={() => router.push(`/class/${nextClass.id}` as never)} style={({ pressed }) => [styles.nextCard, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.82 : 1 }]}><Text style={[styles.nextLabel, { color: colors.tint, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "الدرس القادم" : "NEXT DARS"}</Text><Text numberOfLines={2} style={[styles.nextTitle, { color: colors.text }, writing]}>{nextClass.title}</Text><Text numberOfLines={1} style={[styles.nextTeacher, { color: colors.muted }, writing]}>{teacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text><View style={[styles.nextFooter, isRTL && styles.rowReverse]}><View style={[styles.nextMeta, isRTL && styles.rowReverse]}><MaterialIcons name="schedule" size={15} color={colors.tint} /><Text style={[styles.nextMetaText, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatTime(nextClass.startTime, locale)}</Text><Text style={[styles.separator, { color: colors.muted }]}>·</Text><Text numberOfLines={1} style={[styles.nextMetaText, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{location?.name ?? nextClass.city}</Text></View><MaterialIcons name={isRTL ? "arrow-back" : "arrow-forward"} size={19} color={colors.tint} /></View></MotionPressable> : null}<View style={[styles.sectionHead, isRTL && styles.rowReverse]}><Text style={[styles.sectionTitle, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "القادم" : "Upcoming"}</Text>{upcoming.length > 2 ? <MotionPressable onPress={() => router.push("/schedule" as never)}><Text style={[styles.allLink, { color: colors.tint, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "عرض الكل" : "See all"}</Text></MotionPressable> : null}</View></View>;
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={upcoming} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) }]} ListHeaderComponent={header} renderItem={({ item }) => { const rowTeacher = getRef(teachers, item.teacherId); return <MotionPressable accessibilityRole="button" onPress={() => router.push(`/class/${item.id}` as never)} style={({ pressed }) => [styles.row, isRTL && styles.rowReverse, { borderBottomColor: colors.border, opacity: pressed ? 0.66 : 1 }]}><Text style={[styles.time, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatTime(item.startTime, locale)}</Text><View style={styles.timeline}><View style={[styles.dot, { backgroundColor: colors.tint, borderColor: colors.background }]} /></View><View style={styles.rowCopy}><Text numberOfLines={1} style={[styles.rowTitle, { color: colors.text }, writing]}>{item.title}</Text><Text numberOfLines={1} style={[styles.rowMeta, { color: colors.muted }, writing]}>{rowTeacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={colors.muted} /></MotionPressable>; }} ListEmptyComponent={<View style={styles.empty}>{hasReferences ? <EmptyState icon="event-available" title={language === "ar" ? "لا دروس قادمة" : "No classes yet"} message={language === "ar" ? "أضف درساً عندما تكون مستعداً." : "Add a class when you are ready."} actionLabel={language === "ar" ? "أضف درساً" : "Add class"} onAction={() => router.push("/class/form" as never)} /> : <EmptyState icon="auto-stories" title={language === "ar" ? "ابدأ من هنا" : "Start here"} message={language === "ar" ? "أضف معلماً وكتاباً ومكاناً أولاً." : "Add a teacher, book, and place first."} actionLabel={firstSetup.label} onAction={() => router.push(firstSetup.route as never)} />}</View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, rowReverse: { flexDirection: "row-reverse" }, header: { gap: 24, paddingBottom: 12, paddingTop: 10 }, topLine: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, greeting: { fontSize: 31, fontWeight: "700", letterSpacing: -1.3, lineHeight: 38 }, date: { fontSize: 12.5, marginTop: 3 }, nextCard: { borderRadius: 23, borderWidth: StyleSheet.hairlineWidth, gap: 7, padding: 21, shadowColor: "#143E32", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.06, shadowRadius: 20 }, nextLabel: { fontSize: 10.5, fontWeight: "800", letterSpacing: 0.9 }, nextTitle: { fontSize: 23, fontWeight: "700", letterSpacing: -0.6, lineHeight: 29, marginTop: 2 }, nextTeacher: { fontSize: 13.5 }, nextFooter: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 10 }, nextMeta: { alignItems: "center", flex: 1, flexDirection: "row", gap: 6, minWidth: 0 }, nextMetaText: { fontSize: 12.5, fontWeight: "700", maxWidth: 125 }, separator: { fontSize: 15 }, sectionHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 2 }, sectionTitle: { fontSize: 17, fontWeight: "700", letterSpacing: -0.25 }, allLink: { fontSize: 13, fontWeight: "700" }, row: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 70 }, time: { fontSize: 12.5, fontWeight: "700", textAlign: "center", width: 58 }, timeline: { alignItems: "center", width: 21 }, dot: { borderRadius: 9, borderWidth: 3, height: 11, width: 11 }, rowCopy: { flex: 1, gap: 2, minWidth: 0 }, rowTitle: { fontSize: 15.5, fontWeight: "700" }, rowMeta: { fontSize: 12.5 }, empty: { paddingTop: 12 }, loading: { gap: 18, padding: 20, paddingTop: 34 }, loadTitle: { borderRadius: 8, height: 34, width: 170 }, loadHero: { borderRadius: 23, height: 174, width: "100%" } });
