import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ClassCard, EmptyState, FilterChips, IconButton } from "@/components/dars-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { dayDifference, formatClassDate, formatTime, getNextClass, getRef, getUpcomingClasses } from "@/lib/dars-utils";
import { useDars } from "@/lib/dars-context";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

export default function HomeScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { classes, teachers, books, locations } = useDars(); const [range, setRange] = useState("Today"); const upcoming = useMemo(() => getUpcomingClasses(classes), [classes]); const nextClass = getNextClass(classes);
  const visible = useMemo(() => upcoming.filter((item) => { const distance = dayDifference(item.date); return range === "Today" ? distance === 0 : range === "This Week" ? distance >= 0 && distance <= 7 : true; }), [range, upcoming]);
  const featureLabel = !nextClass ? "" : dayDifference(nextClass.date) === 0 ? "NEXT CLASS TODAY" : dayDifference(nextClass.date) === 1 ? "NEXT CLASS TOMORROW" : `NEXT CLASS ${formatClassDate(nextClass.date).toUpperCase()}`;
  const header = <View style={styles.header}><View style={styles.topbar}><View><Text style={[styles.greeting, { color: colors.text }]}>Assalamu alaykum</Text><Text style={[styles.subGreeting, { color: colors.muted }]}>Here’s what’s next</Text></View><IconButton icon="settings" label="Settings" onPress={() => router.push("/settings" as never)} /></View>{nextClass ? <Pressable onPress={() => router.push(`/class/${nextClass.id}` as never)} style={({ pressed }) => [styles.featureCard, { backgroundColor: colors.tint, opacity: pressed ? 0.85 : 1, transform: [{ scale: pressed ? 0.99 : 1 }] }]}><View style={styles.featureTop}><View><Text style={[styles.featureOverline, { color: colors.background }]}>{featureLabel}</Text><Text style={[styles.featureTime, { color: colors.background }]}>{formatTime(nextClass.startTime)}</Text></View><View style={[styles.motif, { backgroundColor: colors.surface }]}><MaterialIcons name="auto-stories" size={37} color={colors.tint} /><MaterialIcons name="nightlight-round" size={14} color={colors.text} style={styles.moon} /></View></View><Text numberOfLines={2} style={[styles.featureTitle, { color: colors.background }]}>{nextClass.title}</Text><View style={styles.featureMeta}><MaterialIcons name="person-outline" size={15} color={colors.background} /><Text style={[styles.featureMetaText, { color: colors.background }]}>{getRef(teachers, nextClass.teacherId)?.name ?? "Teacher pending"}</Text></View><View style={styles.featureMeta}><MaterialIcons name="location-on" size={15} color={colors.background} /><Text numberOfLines={1} style={[styles.featureMetaText, { color: colors.background }]}>{getRef(locations, nextClass.locationId)?.name ?? nextClass.city}</Text></View><View style={[styles.viewDetails, { borderColor: colors.background }]}><Text style={[styles.viewDetailsText, { color: colors.background }]}>View details</Text><MaterialIcons name="arrow-forward" size={17} color={colors.background} /></View></Pressable> : null}<View style={styles.upcomingHeader}><Text style={[styles.upcomingTitle, { color: colors.text }]}>Upcoming Classes</Text><FilterChips values={["Today", "This Week", "All"]} selected={range} onSelect={setRange} /></View></View>;
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={visible} keyExtractor={(item) => item.id} renderItem={({ item }) => <View style={styles.cardWrap}><ClassCard item={item} teachers={teachers} books={books} locations={locations} /></View>} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) }]} ListHeaderComponent={header} ListEmptyComponent={<EmptyState title="Nothing planned" message="Your schedule is clear for this view." />} ListFooterComponent={<View style={styles.footer}><Pressable accessibilityLabel="Add a class" onPress={() => router.push("/class/form" as never)} style={({ pressed }) => [styles.quickAdd, { backgroundColor: colors.tint, opacity: pressed ? 0.75 : 1, transform: [{ scale: pressed ? 0.96 : 1 }] }]}><MaterialIcons name="add" size={25} color={colors.background} /></Pressable></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 18 }, header: { gap: 19, paddingTop: 7, paddingBottom: 17 }, topbar: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, greeting: { fontSize: 22, fontWeight: "800", letterSpacing: -0.4 }, subGreeting: { fontSize: 13, marginTop: 2 }, featureCard: { borderRadius: 18, gap: 8, overflow: "hidden", padding: 18, shadowColor: "#0B2D22", shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.17, shadowRadius: 16 }, featureTop: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, featureOverline: { fontSize: 11, fontWeight: "700", letterSpacing: 0.5, opacity: 0.8 }, featureTime: { fontSize: 25, fontWeight: "800", lineHeight: 31, marginTop: 3 }, motif: { alignItems: "center", borderRadius: 18, height: 61, justifyContent: "center", width: 61 }, moon: { position: "absolute", right: 10, top: 10 }, featureTitle: { fontSize: 15, fontWeight: "800", lineHeight: 21, maxWidth: "85%" }, featureMeta: { alignItems: "center", flexDirection: "row", gap: 6 }, featureMetaText: { flex: 1, fontSize: 12.5, lineHeight: 18, opacity: 0.86 }, viewDetails: { alignItems: "center", borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 7, justifyContent: "center", marginTop: 5, minHeight: 39, opacity: 0.78 }, viewDetailsText: { fontSize: 12.5, fontWeight: "800" }, upcomingHeader: { gap: 11, marginTop: 1 }, upcomingTitle: { fontSize: 16, fontWeight: "800" }, cardWrap: { marginBottom: 10 }, footer: { alignItems: "flex-end", paddingTop: 11 }, quickAdd: { alignItems: "center", borderRadius: 27, elevation: 4, height: 54, justifyContent: "center", shadowColor: "#0B2D22", shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.2, shadowRadius: 8, width: 54 } });
