import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, StyleSheet, View } from "react-native";
import { DirectoryRow, EmptyState, FilterChips, IconButton, ScreenTitle, SearchField } from "@/components/dars-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useDars } from "@/lib/dars-context";
import { useI18n } from "@/lib/i18n";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

type LibraryKind = "teachers" | "books" | "places";
export default function LibraryScreen() {
  const { teachers, books, locations, classes } = useDars(); const { language } = useI18n(); const insets = useSafeAreaInsets(); const [kind, setKind] = useState<LibraryKind>("teachers"); const [query, setQuery] = useState(""); const labels: Record<LibraryKind, string> = { teachers: language === "ar" ? "المعلمون" : "Teachers", books: language === "ar" ? "الكتب" : "Books", places: language === "ar" ? "الأماكن" : "Places" }; const items = useMemo(() => { const q = query.trim().toLocaleLowerCase(); const source = kind === "teachers" ? teachers.map((item) => ({ id: item.id, title: item.name, subtitle: item.subjects.join(" · "), icon: "groups" as const, route: `/teacher/${item.id}`, tag: `${classes.filter((entry) => entry.teacherId === item.id).length}` })) : kind === "books" ? books.map((item) => ({ id: item.id, title: item.name, subtitle: [item.author, item.subject].filter(Boolean).join(" · "), icon: "menu-book" as const, route: `/book/${item.id}`, tag: `${classes.filter((entry) => entry.bookId === item.id).length}` })) : locations.map((item) => ({ id: item.id, title: item.name, subtitle: [item.area, item.city].filter(Boolean).join(" · "), icon: "location-on" as const, route: `/location/${item.id}`, tag: `${classes.filter((entry) => entry.locationId === item.id).length}` })); return source.filter((item) => !q || `${item.title} ${item.subtitle}`.toLocaleLowerCase().includes(q)).sort((a, b) => a.title.localeCompare(b.title)); }, [books, classes, kind, locations, query, teachers]); const addPath = kind === "teachers" ? "/teacher/form" : kind === "books" ? "/book/form" : "/location/form";
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) + 16 }]} ListHeaderComponent={<View style={styles.header}><ScreenTitle eyebrow={language === "ar" ? "المكتبة" : "Library"} title={language === "ar" ? "المراجع" : "References"} action={<IconButton icon="add" label={language === "ar" ? "إضافة" : "Add"} onPress={() => router.push(addPath as never)} />} /><FilterChips values={["teachers", "books", "places"]} selected={kind} onSelect={(value) => setKind(value as LibraryKind)} labels={labels} /><View style={styles.search}><SearchField value={query} onChangeText={setQuery} placeholder={language === "ar" ? `ابحث في ${labels[kind]}` : `Search ${labels[kind].toLocaleLowerCase()}`} /></View></View>} renderItem={({ item }) => <DirectoryRow icon={item.icon} title={item.title} subtitle={item.subtitle || (language === "ar" ? "بدون تفاصيل إضافية" : "No additional details")} tag={item.tag} onPress={() => router.push(item.route as never)} />} ListEmptyComponent={<EmptyState icon={kind === "teachers" ? "groups" : kind === "books" ? "menu-book" : "location-on"} title={language === "ar" ? `لا توجد ${labels[kind]}` : `No ${labels[kind].toLocaleLowerCase()} yet`} message={language === "ar" ? "أضف سجلاً لربطه بالدروس." : "Add a reference to connect it with your classes."} actionLabel={language === "ar" ? "إضافة" : `Add ${labels[kind].slice(0, -1)}`} onAction={() => router.push(addPath as never)} />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 16 }, header: { gap: 12, marginBottom: 4 }, search: { marginTop: 1 } });
