import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, SectionList, StyleSheet, Text, View } from "react-native";
import { EmptyState } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { dayDifference, formatClassDate, formatTime, getRef, getUpcomingClasses } from "@/lib/dars-utils";
import { useDars } from "@/lib/dars-context";
import { useDisplayPreferences } from "@/lib/use-display-preferences";
import { useI18n } from "@/lib/i18n";
import type { DarsClass } from "@/lib/types/dars";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

type ScheduleGroup = { title: string; date: string; data: DarsClass[] };
const dateAt = (offset: number) => { const date = new Date(); date.setDate(date.getDate() + offset); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };

export default function ScheduleScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { classes, teachers, isHydrated } = useDars(); const { dateDisplay, locale } = useDisplayPreferences(); const { language, isRTL } = useI18n(); const [view, setView] = useState<"today" | "week">("today"); const [day, setDay] = useState(0); const dates = useMemo(() => [-1, 0, 1, 2, 3].map((offset) => ({ offset, date: dateAt(offset) })), []);
  const sections = useMemo<ScheduleGroup[]>(() => { const items = getUpcomingClasses(classes).filter((item) => view === "today" ? item.date === dateAt(day) : dayDifference(item.date) >= Math.max(0, day) && dayDifference(item.date) <= Math.max(0, day) + 6); return Object.entries(items.reduce<Record<string, DarsClass[]>>((acc, item) => { (acc[item.date] ??= []).push(item); return acc; }, {})).map(([date, data]) => ({ date, title: dayDifference(date) === 0 ? (language === "ar" ? "اليوم" : "Today") : formatClassDate(date, dateDisplay, locale), data })); }, [classes, dateDisplay, day, language, locale, view]);
  const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  if (!isHydrated) return <ScreenContainer edges={["top", "left", "right"]}><View style={styles.loading}><View style={[styles.loadTitle, { backgroundColor: colors.wash }]} /><View style={[styles.loadRow, { backgroundColor: colors.wash }]} /></View></ScreenContainer>;
  const header = <View style={styles.header}><View style={styles.headerTop}><Text style={[styles.title, { color: colors.text }, writing]}>{language === "ar" ? "الجدول" : "Schedule"}</Text><View style={[styles.viewToggle, isRTL && styles.rowReverse]}><ViewToggle label={language === "ar" ? "يوم" : "Day"} active={view === "today"} onPress={() => setView("today")} /><ViewToggle label={language === "ar" ? "أسبوع" : "Week"} active={view === "week"} onPress={() => setView("week")} /></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.dateStrip, isRTL && styles.rowReverse]}>{dates.map(({ offset, date }) => <Pressable key={date} onPress={() => { setDay(offset); setView("today"); }} style={({ pressed }) => [styles.dateItem, { borderBottomColor: day === offset ? colors.tint : "transparent", opacity: pressed ? 0.62 : 1 }]}><Text style={[styles.dow, { color: day === offset ? colors.tint : colors.muted }]}>{new Date(`${date}T12:00:00`).toLocaleDateString(locale, { weekday: "short" })}</Text><Text style={[styles.dnum, { color: day === offset ? colors.text : colors.muted }]}>{new Date(`${date}T12:00:00`).getDate()}</Text></Pressable>)}</ScrollView></View>;
  return <ScreenContainer edges={["top", "left", "right"]}><SectionList sections={sections} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) + 16 }]} ListHeaderComponent={header} renderSectionHeader={({ section }) => <Text style={[styles.dayLabel, { color: colors.muted }, writing]}>{section.title}</Text>} renderItem={({ item }) => { const teacher = getRef(teachers, item.teacherId); return <MotionPressable accessibilityRole="button" onPress={() => router.push(`/class/${item.id}` as never)} style={({ pressed }) => [styles.classRow, isRTL && styles.rowReverse, { borderColor: colors.border, opacity: pressed ? 0.64 : 1 }]}><View style={styles.timeBlock}><Text style={[styles.time, { color: colors.tint, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatTime(item.startTime, locale)}</Text></View><View style={styles.rowBody}><Text numberOfLines={1} style={[styles.rowTitle, { color: colors.text }, writing]}>{item.title}</Text><Text numberOfLines={1} style={[styles.rowMeta, { color: colors.muted }, writing]}>{teacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={colors.muted} /></MotionPressable>; }} ListEmptyComponent={<EmptyState icon="event-available" title={language === "ar" ? "لا دروس هنا" : "No classes here"} message={language === "ar" ? "اختر يوماً آخر أو أضف درساً." : "Try another day or add a class."} actionLabel={language === "ar" ? "أضف درساً" : "Add class"} onAction={() => router.push("/class/form" as never)} />} /></ScreenContainer>;
}

function ViewToggle({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.toggleButton, { backgroundColor: active ? colors.wash : "transparent", opacity: pressed ? 0.66 : 1 }]}><Text style={[styles.toggleText, { color: active ? colors.tint : colors.muted }]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, rowReverse: { flexDirection: "row-reverse" }, header: { paddingBottom: 18, paddingTop: 8 }, headerTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, title: { fontSize: 29, fontWeight: "700", letterSpacing: -0.85, lineHeight: 35 }, viewToggle: { flexDirection: "row", gap: 2 }, toggleButton: { borderRadius: 9, minHeight: 34, paddingHorizontal: 10, paddingVertical: 8 }, toggleText: { fontSize: 12, fontWeight: "800" }, dateStrip: { gap: 16, paddingTop: 23 }, dateItem: { alignItems: "center", borderBottomWidth: 2, minWidth: 38, paddingBottom: 8 }, dow: { fontSize: 10, fontWeight: "700" }, dnum: { fontSize: 17, fontWeight: "700", marginTop: 4 }, dayLabel: { fontSize: 10.5, fontWeight: "800", letterSpacing: 0.75, marginBottom: 7, marginTop: 3 }, classRow: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 13, minHeight: 70 }, timeBlock: { alignItems: "center", justifyContent: "center", width: 58 }, time: { fontSize: 12, fontWeight: "800" }, rowBody: { flex: 1, gap: 3, minWidth: 0, paddingVertical: 13 }, rowTitle: { fontSize: 15, fontWeight: "700", lineHeight: 20 }, rowMeta: { fontSize: 12.5 }, loading: { gap: 16, padding: 20, paddingTop: 30 }, loadTitle: { borderRadius: 7, height: 32, width: 120 }, loadRow: { borderRadius: 12, height: 70, width: "100%" } });
