import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, SectionList, StyleSheet, Text, View } from "react-native";
import { EmptyState } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { dayDifference, formatClassDate, formatTime, getRef, getUpcomingClasses } from "@/lib/dars-utils";
import { useDars } from "@/lib/dars-context";
import { useDisplayPreferences } from "@/lib/use-display-preferences";
import { useI18n } from "@/lib/i18n";
import type { DarsClass } from "@/lib/types/dars";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

type ScheduleGroup = { title: string; date: string; data: DarsClass[] };

export default function ScheduleScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { classes, teachers, isHydrated } = useDars(); const { dateDisplay, locale } = useDisplayPreferences(); const { language, isRTL } = useI18n(); const [view, setView] = useState<"today" | "week">("today");
  const sections = useMemo<ScheduleGroup[]>(() => { const items = getUpcomingClasses(classes).filter((item) => view === "today" ? dayDifference(item.date) === 0 : dayDifference(item.date) >= 0 && dayDifference(item.date) <= 7); return Object.entries(items.reduce<Record<string, DarsClass[]>>((acc, item) => { (acc[item.date] ??= []).push(item); return acc; }, {})).map(([date, data]) => ({ date, title: dayDifference(date) === 0 ? (language === "ar" ? "اليوم" : "Today") : formatClassDate(date, dateDisplay, locale), data })); }, [classes, dateDisplay, language, locale, view]);
  const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  if (!isHydrated) return <ScreenContainer edges={["top", "left", "right"]}><View style={styles.loading}><View style={[styles.loadTitle, { backgroundColor: colors.wash }]} /><View style={[styles.loadRow, { backgroundColor: colors.wash }]} /></View></ScreenContainer>;
  const header = <View style={styles.header}><Text style={[styles.title, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "الجدول" : "Agenda"}</Text><View style={[styles.tabs, isRTL && styles.rowReverse]}><Tab label={language === "ar" ? "اليوم" : "Today"} active={view === "today"} onPress={() => setView("today")} /><Tab label={language === "ar" ? "الأسبوع" : "Week"} active={view === "week"} onPress={() => setView("week")} /></View></View>;
  return <ScreenContainer edges={["top", "left", "right"]}><SectionList sections={sections} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) }]} ListHeaderComponent={header} renderSectionHeader={({ section }) => <View style={[styles.sectionHead, isRTL && styles.rowReverse]}><Text style={[styles.sectionTitle, { color: colors.text }, writing]}>{section.title}</Text><View style={[styles.sectionRule, { backgroundColor: colors.border }]} /></View>} renderItem={({ item }) => { const teacher = getRef(teachers, item.teacherId); return <MotionPressable accessibilityRole="button" onPress={() => router.push(`/class/${item.id}` as never)} style={({ pressed }) => [styles.timelineRow, isRTL && styles.rowReverse, { opacity: pressed ? 0.66 : 1 }]}><Text style={[styles.time, { color: colors.text, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatTime(item.startTime, locale)}</Text><View style={styles.timeline}><View style={[styles.dot, { backgroundColor: colors.tint }]} /><View style={[styles.line, { backgroundColor: colors.border }]} /></View><View style={styles.itemCopy}><Text numberOfLines={1} style={[styles.itemTitle, { color: colors.text }, writing]}>{item.title}</Text><Text numberOfLines={1} style={[styles.itemMeta, { color: colors.muted }, writing]}>{teacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={colors.muted} /></MotionPressable>; }} ListEmptyComponent={<EmptyState icon="event-available" title={view === "today" ? (language === "ar" ? "لا دروس اليوم" : "Nothing today") : (language === "ar" ? "الأسبوع هادئ" : "A quiet week")} message={language === "ar" ? "أضف درساً عندما تكون مستعداً." : "Add a class when you are ready."} actionLabel={language === "ar" ? "أضف درساً" : "Add class"} onAction={() => router.push("/class/form" as never)} />} /></ScreenContainer>;
}

function Tab({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.tab, { borderBottomColor: active ? colors.tint : "transparent", opacity: pressed ? 0.68 : 1 }]}><Text style={[styles.tabText, { color: active ? colors.text : colors.muted }]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, rowReverse: { flexDirection: "row-reverse" }, header: { gap: 20, paddingBottom: 27, paddingTop: 10 }, title: { fontSize: 34, fontWeight: "700", letterSpacing: -1.4, lineHeight: 40 }, tabs: { alignSelf: "flex-start", flexDirection: "row", gap: 18 }, tab: { borderBottomWidth: 2, minHeight: 31, paddingBottom: 7 }, tabText: { fontSize: 13, fontWeight: "700" }, sectionHead: { alignItems: "center", flexDirection: "row", gap: 10, paddingBottom: 8, paddingTop: 2 }, sectionTitle: { fontSize: 14, fontWeight: "700" }, sectionRule: { flex: 1, height: StyleSheet.hairlineWidth }, timelineRow: { alignItems: "stretch", flexDirection: "row", minHeight: 84 }, time: { fontSize: 13, fontWeight: "700", paddingTop: 11, textAlign: "center", width: 58 }, timeline: { alignItems: "center", width: 23 }, dot: { borderColor: "#FFFFFF", borderRadius: 99, borderWidth: 3, height: 12, marginTop: 13, width: 12, zIndex: 1 }, line: { bottom: 0, position: "absolute", top: 24, width: StyleSheet.hairlineWidth }, itemCopy: { flex: 1, gap: 3, paddingBottom: 15, paddingTop: 8 }, itemTitle: { fontSize: 16, fontWeight: "700", lineHeight: 21 }, itemMeta: { fontSize: 12.5, lineHeight: 18 }, loading: { gap: 16, padding: 20, paddingTop: 30 }, loadTitle: { borderRadius: 8, height: 36, width: 130 }, loadRow: { borderRadius: 10, height: 68, width: "100%" } });
