import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, SectionList, StyleSheet, Text, View } from "react-native";
import { EmptyState } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { dayDifference, formatClassDate, formatTime, getRef, getUpcomingClasses } from "@/lib/dars-utils";
import { useDars } from "@/lib/dars-context";
import { useDisplayPreferences } from "@/lib/use-display-preferences";
import { useI18n } from "@/lib/i18n";
import type { DarsClass } from "@/lib/types/dars";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

type ScheduleGroup = { title: string; date: string; data: DarsClass[] };
const dateAt = (offset: number) => { const d = new Date(); d.setDate(d.getDate() + offset); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };

export default function ScheduleScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { classes, teachers, isHydrated } = useDars(); const { dateDisplay, locale } = useDisplayPreferences(); const { language, isRTL } = useI18n(); const [view, setView] = useState<"today" | "week">("today"); const [day, setDay] = useState(0); const dates = useMemo(() => [-1, 0, 1, 2, 3].map((offset) => ({ offset, date: dateAt(offset) })), []);
  const sections = useMemo<ScheduleGroup[]>(() => { const items = getUpcomingClasses(classes).filter((item) => view === "today" ? item.date === dateAt(day) : dayDifference(item.date) >= Math.max(0, day) && dayDifference(item.date) <= Math.max(0, day) + 6); return Object.entries(items.reduce<Record<string, DarsClass[]>>((acc, item) => { (acc[item.date] ??= []).push(item); return acc; }, {})).map(([date, data]) => ({ date, title: dayDifference(date) === 0 ? (language === "ar" ? "اليوم" : "Today") : formatClassDate(date, dateDisplay, locale), data })); }, [classes, dateDisplay, day, language, locale, view]);
  const writing = { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const };
  if (!isHydrated) return <ScreenContainer edges={["top", "left", "right"]}><View style={styles.loading}><View style={[styles.loadTitle, { backgroundColor: colors.wash }]} /><View style={[styles.loadRow, { backgroundColor: colors.wash }]} /></View></ScreenContainer>;
  const header = <View style={styles.header}><Text style={[styles.title, { color: colors.tint, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "الجدول" : "Schedule"}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.dateStrip, isRTL && styles.rowReverse]}>{dates.map(({ offset, date }) => <Pressable key={date} onPress={() => { setDay(offset); setView("today"); }} style={({ pressed }) => [styles.datePill, { backgroundColor: day === offset ? colors.tint : colors.surface, borderColor: day === offset ? colors.tint : colors.border, opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.dow, { color: day === offset ? colors.background : colors.muted }]}>{new Date(`${date}T12:00:00`).toLocaleDateString(locale, { weekday: "short" })}</Text><Text style={[styles.dnum, { color: day === offset ? colors.background : colors.text }]}>{new Date(`${date}T12:00:00`).getDate()}</Text></Pressable>)}</ScrollView><View style={[styles.segmented, { backgroundColor: colors.wash }, isRTL && styles.rowReverse]}><Segment label={language === "ar" ? "اليوم" : "Day"} active={view === "today"} onPress={() => setView("today")} /><Segment label={language === "ar" ? "الأسبوع" : "Week"} active={view === "week"} onPress={() => setView("week")} /></View></View>;
  return <ScreenContainer edges={["top", "left", "right"]}><SectionList sections={sections} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) }]} ListHeaderComponent={header} renderSectionHeader={({ section }) => <Text style={[styles.dayLabel, { color: colors.muted, textAlign: isRTL ? "right" : "left", writingDirection: isRTL ? "rtl" : "ltr" }]}>{section.title}</Text>} renderItem={({ item }) => { const teacher = getRef(teachers, item.teacherId); return <MotionPressable accessibilityRole="button" onPress={() => router.push(`/class/${item.id}` as never)} style={({ pressed }) => [styles.classRow, isRTL && styles.rowReverse, { backgroundColor: colors.surface, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.timeBlock, { borderColor: colors.border }]}><Text style={[styles.time, { color: colors.tint, writingDirection: isRTL ? "rtl" : "ltr" }]}>{formatTime(item.startTime, locale)}</Text><Text style={[styles.timeCaption, { color: colors.muted }]}>{language === "ar" ? "درس" : "DARS"}</Text></View><View style={styles.rowBody}><Text numberOfLines={1} style={[styles.rowTitle, { color: colors.text }, writing]}>{item.title}</Text><Text numberOfLines={1} style={[styles.rowMeta, { color: colors.muted }, writing]}>{teacher?.name ?? (language === "ar" ? "المعلم غير محدد" : "Teacher pending")}</Text></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={colors.muted} /></MotionPressable>; }} ListEmptyComponent={<EmptyState icon="event-available" title={language === "ar" ? "لا دروس هنا" : "No classes here"} message={language === "ar" ? "اختر يوماً آخر أو أضف درساً." : "Try another day or add a class."} actionLabel={language === "ar" ? "أضف درساً" : "Add class"} onAction={() => router.push("/class/form" as never)} />} /></ScreenContainer>;
}

function Segment({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.segment, { backgroundColor: active ? colors.surface : "transparent", opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.segmentText, { color: active ? colors.tint : colors.muted }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 22 }, rowReverse: { flexDirection: "row-reverse" }, header: { gap: 14, paddingBottom: 20, paddingTop: 8 }, title: { fontFamily: "serif", fontSize: 26, fontWeight: "700", lineHeight: 32 }, dateStrip: { gap: 9, paddingVertical: 2 }, datePill: { alignItems: "center", borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, paddingVertical: 11, width: 52 }, dow: { fontSize: 9.5, fontWeight: "700" }, dnum: { fontSize: 16, fontWeight: "800", marginTop: 3 }, segmented: { borderRadius: 999, flexDirection: "row", padding: 4 }, segment: { alignItems: "center", borderRadius: 999, flex: 1, paddingVertical: 9 }, segmentText: { fontSize: 12.5, fontWeight: "700" }, dayLabel: { fontSize: 11.5, fontWeight: "800", letterSpacing: 0.6, marginBottom: 10, marginTop: 6 }, classRow: { alignItems: "center", borderRadius: 18, flexDirection: "row", gap: 13, marginBottom: 9, minHeight: 72, paddingHorizontal: 14, shadowColor: "#16332B", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.05, shadowRadius: 12 }, timeBlock: { borderEndWidth: StyleSheet.hairlineWidth, minWidth: 52, paddingEnd: 11 }, time: { fontSize: 13, fontWeight: "800", textAlign: "center" }, timeCaption: { fontSize: 9.5, fontWeight: "700", letterSpacing: 0.4, marginTop: 1, textAlign: "center" }, rowBody: { flex: 1, gap: 2, minWidth: 0 }, rowTitle: { fontSize: 14.5, fontWeight: "700" }, rowMeta: { fontSize: 12 }, loading: { gap: 16, padding: 22, paddingTop: 30 }, loadTitle: { borderRadius: 8, height: 34, width: 130 }, loadRow: { borderRadius: 18, height: 72, width: "100%" } });
