import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { EmptyState, IconButton, SearchField } from "@/components/dars-ui";
import { MotionPressable } from "@/components/motion-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { useI18n } from "@/lib/i18n";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

const initial = (name: string) => name.replace(/^(Shaykh|Ustadh)\s+/i, "").split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();

export default function TeachersScreen() {
  const colors = useColors(); const { teachers } = useDars(); const insets = useSafeAreaInsets(); const { isRTL, language } = useI18n(); const [query, setQuery] = useState(""); const [searching, setSearching] = useState(false); const list = useMemo(() => teachers.filter((teacher) => `${teacher.name} ${teacher.subjects.join(" ")}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [query, teachers]); const text = (color: string) => ({ color, textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const });
  const header = <View style={styles.header}><View style={[styles.topLine, isRTL && styles.rowReverse]}><Text style={[styles.title, { color: colors.tint, writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "ar" ? "المعلمون" : "Teachers"}</Text><View style={[styles.actions, isRTL && styles.rowReverse]}><IconButton icon={searching ? "close" : "search"} label={language === "ar" ? "بحث" : "Search"} onPress={() => { setSearching((value) => !value); setQuery(""); }} /><IconButton icon="add" tone="primary" label={language === "ar" ? "أضف معلماً" : "Add teacher"} onPress={() => router.push("/teacher/form" as never)} /></View></View>{searching ? <SearchField value={query} onChangeText={setQuery} placeholder={language === "ar" ? "ابحث باسم المعلم" : "Search teachers"} /> : null}</View>;
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={list} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) }]} ListHeaderComponent={header} renderItem={({ item }) => <MotionPressable accessibilityRole="button" onPress={() => router.push(`/teacher/${item.id}` as never)} style={({ pressed }) => [styles.teacherRow, isRTL && styles.rowReverse, { backgroundColor: colors.surface, opacity: pressed ? 0.66 : 1 }]}><View style={[styles.avatar, { backgroundColor: colors.wash }]}><Text style={[styles.avatarText, { color: colors.tint }]}>{initial(item.name)}</Text></View><View style={styles.teacherCopy}><Text numberOfLines={1} style={[styles.teacherName, text(colors.text)]}>{item.name}</Text><Text numberOfLines={1} style={[styles.teacherSubjects, text(colors.muted)]}>{item.subjects.slice(0, 2).join(" · ")}</Text></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={colors.muted} /></MotionPressable>} ListEmptyComponent={<EmptyState icon="groups" title={language === "ar" ? "لا يوجد معلمون" : "No teachers yet"} message={language === "ar" ? "أضف معلماً للبدء." : "Add a teacher to begin."} actionLabel={language === "ar" ? "أضف معلماً" : "Add teacher"} onAction={() => router.push("/teacher/form" as never)} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 22 }, rowReverse: { flexDirection: "row-reverse" }, header: { gap: 18, marginBottom: 15, paddingTop: 8 }, topLine: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, title: { fontFamily: "serif", fontSize: 26, fontWeight: "700", lineHeight: 32 }, actions: { flexDirection: "row", gap: 8 }, teacherRow: { alignItems: "center", borderRadius: 18, flexDirection: "row", gap: 13, marginBottom: 9, minHeight: 72, paddingHorizontal: 14, shadowColor: "#16332B", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.05, shadowRadius: 12 }, avatar: { alignItems: "center", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, avatarText: { fontFamily: "serif", fontSize: 15, fontWeight: "700" }, teacherCopy: { flex: 1, gap: 2, minWidth: 0 }, teacherName: { fontSize: 14.5, fontWeight: "700", lineHeight: 21 }, teacherSubjects: { fontSize: 12, lineHeight: 18 } });
