import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { EmptyState, IconButton, ScreenTitle, SearchField } from "@/components/dars-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { formatTime, getUpcomingClasses } from "@/lib/dars-utils";
import { useI18n } from "@/lib/i18n";
import { getTabListBottomPadding } from "@/lib/responsive-layout";
import { useSafeAreaInsets } from "react-native-safe-area-context";

const initial = (name: string) => name.replace(/^(Shaykh|Ustadh)\s+/i, "").split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();

export default function TeachersScreen() {
  const colors = useColors(); const { teachers, classes } = useDars(); const insets = useSafeAreaInsets(); const { isRTL, language } = useI18n(); const [query, setQuery] = useState(""); const list = useMemo(() => teachers.filter((teacher) => `${teacher.name} ${teacher.subjects.join(" ")}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [query, teachers]);
  const text = (color: string) => ({ color, textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const });
  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={list} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, { paddingBottom: getTabListBottomPadding(insets.bottom) }]} ListHeaderComponent={<View style={styles.header}><ScreenTitle title={language === "ar" ? "المعلمون" : "Teachers"} action={<IconButton icon="add" label={language === "ar" ? "أضف معلماً" : "Add teacher"} tone="primary" onPress={() => router.push("/teacher/form" as never)} />} /><SearchField value={query} onChangeText={setQuery} placeholder={language === "ar" ? "ابحث باسم المعلم أو المادة" : "Search teachers or subjects"} /><Text style={[styles.count, { color: colors.muted, writingDirection: isRTL ? "rtl" : "ltr" }]}>{list.length ? `${list.length} ${language === "ar" ? "في الدليل" : "in your directory"}` : ""}</Text></View>} renderItem={({ item }) => { const next = getUpcomingClasses(classes).find((entry) => entry.teacherId === item.id); return <Pressable accessibilityRole="button" onPress={() => router.push(`/teacher/${item.id}` as never)} style={({ pressed }) => [styles.teacherRow, isRTL && styles.rowReverse, { borderColor: colors.border, opacity: pressed ? 0.68 : 1 }]}><View style={[styles.avatar, { backgroundColor: colors.wash }]}><Text style={[styles.avatarText, { color: colors.tint }]}>{initial(item.name)}</Text></View><View style={styles.teacherCopy}><View style={[styles.teacherTop, isRTL && styles.rowReverse]}><Text numberOfLines={1} style={[styles.teacherName, text(colors.text)]}>{item.name}</Text><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={colors.muted} /></View><Text numberOfLines={1} style={[styles.teacherSubjects, text(colors.muted)]}>{item.subjects.join(" · ")}</Text>{next ? <Text numberOfLines={1} style={[styles.nextText, text(colors.tint)]}>{formatTime(next.startTime)} · {next.title}</Text> : null}</View></Pressable>; }} ListEmptyComponent={<EmptyState icon="groups" title={language === "ar" ? "لا يوجد معلمون" : "No teachers yet"} message={language === "ar" ? "أضف معلماً لبدء تنظيم دروسك." : "Add a teacher to start organizing classes."} actionLabel={language === "ar" ? "أضف معلماً" : "Add teacher"} onAction={() => router.push("/teacher/form" as never)} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20 }, rowReverse: { flexDirection: "row-reverse" }, header: { gap: 14, marginBottom: 10 }, count: { fontSize: 12.5, marginTop: 1 }, teacherRow: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 13, minHeight: 84, paddingVertical: 12 }, avatar: { alignItems: "center", borderRadius: 17, height: 50, justifyContent: "center", width: 50 }, avatarText: { fontSize: 15, fontWeight: "800" }, teacherCopy: { flex: 1, gap: 4, minWidth: 0 }, teacherTop: { alignItems: "center", flexDirection: "row", gap: 7, justifyContent: "space-between" }, teacherName: { flex: 1, fontSize: 16, fontWeight: "700", lineHeight: 21 }, teacherSubjects: { fontSize: 12, lineHeight: 17 }, nextText: { fontSize: 11.5, fontWeight: "700", lineHeight: 16, marginTop: 1 } });
