import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Linking, FlatList, StyleSheet, Text, View } from "react-native";
import { ClassCard, EmptyState, IconButton, PrimaryButton, ScreenTitle } from "@/components/dars-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useDars } from "@/lib/dars-context";
import { goBackOrHome } from "@/lib/navigation";

export default function LocationDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const colors = useColors(); const { locations, classes, teachers, books } = useDars(); const location = locations.find((item) => item.id === id); const linked = classes.filter((item) => item.locationId === id);
  if (!location) return <ScreenContainer><EmptyState title="Location not found" message="This place is no longer in your location list." actionLabel="Back to locations" onAction={() => router.replace("/locations" as never)} /></ScreenContainer>;
  return <ScreenContainer><FlatList data={linked} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <View style={styles.item}><ClassCard item={item} teachers={teachers} books={books} locations={locations} /></View>} ListHeaderComponent={<View style={styles.header}><ScreenTitle eyebrow="Class location" title={location.name} action={<IconButton icon="close" label="Close location" onPress={goBackOrHome} />} /><View style={[styles.hero, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.addressRow}><MaterialIcons name="location-on" size={20} color={colors.tint} /><Text style={[styles.address, { color: colors.text }]}>{location.area}, {location.city}</Text></View>{location.address ? <Text style={[styles.addressNote, { color: colors.muted }]}>{location.address}</Text> : null}{location.notes ? <Text style={[styles.notes, { color: colors.text }]}>{location.notes}</Text> : null}<PrimaryButton label="Open map" icon="map" onPress={() => location.mapLink ? Linking.openURL(location.mapLink) : undefined} disabled={!location.mapLink} /></View><Text style={[styles.heading, { color: colors.text }]}>Classes here</Text></View>} ListEmptyComponent={<EmptyState icon="location-on" title="No linked classes" message="Classes held at this location will appear here." />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 36 }, header: { gap: 16, paddingBottom: 8 }, hero: { borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, gap: 11, padding: 16, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 8 }, addressRow: { alignItems: "center", flexDirection: "row", gap: 8 }, address: { fontSize: 15, fontWeight: "600" }, addressNote: { fontSize: 13 }, notes: { fontSize: 13.5, lineHeight: 20 }, heading: { fontSize: 14, fontWeight: "600", marginTop: 2 }, item: { marginTop: 12 } });
